services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kalkulus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kalkulus
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PORT: 8081
      # SMTP configuration
      SMTP_HOST: ${SMTP_HOST:-smtp.domeneshop.no}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME:-your-email-user}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-your-secure-password}
      SMTP_FROM: ${SMTP_FROM:-noreply@yourdomain.no}
      COMPANY_NAME: ${COMPANY_NAME:-YourCompany}
    ports:
      - "8081:8081"

volumes:
  pgdata:
