spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      leak-detection-threshold: 60000
      validation-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    connect-retries: 5
    connect-retries-interval: 10
    default-schema: public
    validate-on-migrate: false
    
jwt:
  secret: ${JWT_SECRET:0d7d52d65f10a246d92b56dea7e705a7ede33c850448cc5ddfa083706dbfc165}

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:3000}

# Logging Configuration for Production
logging:
  level:
    com.timla: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.flywaydb: DEBUG
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server Configuration
server:
  port: ${PORT:8080}  # Railway automatically sets PORT
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Application specific configuration
app:
  jwt:
    secret: ${JWT_SECRET:0d7d52d65f10a246d92b56dea7e705a7ede33c850448cc5ddfa083706dbfc165}
    expiration: 86400000  # 24 hours in milliseconds
  
# Management endpoints (for health checks)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
