server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kalkulus
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
