server:
  port: 8081

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:kalkulus}}
    username: ${JDBC_DATABASE_USERNAME:${PGUSER:postgres}}
    password: ${JDBC_DATABASE_PASSWORD:${PGPASSWORD:postgres}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect